server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/finanzasdb
    username: finanzas_user
    password: "mypassword123"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: finanzas
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: never

app:
  jwt:
    secret: bXktc3VwZXItc2VjcmV0LWtleS1wYXJhLXNwcmluZy1ib290LWZpbmFuemFzLTIwMjYtYXBpLXNlZ3VyYQ==
    expiration-ms: 86400000
