server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  main:
    lazy-initialization: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://finanzas-postgres:5432/finanzasdb}
    username: ${SPRING_DATASOURCE_USERNAME:finanzas_user}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword123}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true
        default_schema: finanzas
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

app:
  jwt:
    secret: ${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS1wYXJhLXNwcmluZy1ib290LWZpbmFuemFzLTIwMjYtYXBpLXNlZ3VyYQ==}
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
