name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build and test
        run: mvn clean verify -e
        env:
          SPRING_PROFILES_ACTIVE: test
          APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          APP_JWT_EXPIRATION_MS: ${{ secrets.APP_JWT_EXPIRATION_MS }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      - name: Print surefire reports
        if: always()
        run: |
          echo "===== Surefire TXT Reports ====="
          find target/surefire-reports -type f -name "*.txt" -print -exec cat {} \;

          echo "===== Surefire XML Reports ====="
          find target/surefire-reports -type f -name "*.xml" -print -exec cat {} \;
